add pytest and port over old tests
Key-Technology/opc-explorer pull request #1
Opened 2024-11-18 22:34 UTC by abrown117

This will make running tests in ci a lot simpler.

2024-11-18 22:40 UTC, kyrofa requested changes

2024-11-18 22:40 UTC, kyrofa commented on tests/test_client.py
> +class TestClient:
Is there a benefit to having a class, here?

2024-11-18 22:40 UTC, kyrofa commented on requirements.txt
> +exceptiongroup==1.2.2
Let's please keep `requirements.txt` to mean "run-time requirements." Make a new `requirements-dev.txt` for these things, and update the workflow to install it as well.

If these are all dependencies from pytest, remove them entirely and only have pytest in the requirements-dev.txt, please.

2024-11-18 22:40 UTC, kyrofa commented on pyproject.toml
> +pythonpath = [".", "uaclient"]
I suspect this isn't actually necessary if you have the package installed before you run tests, can you confirm?

2024-11-18 22:44 UTC, abrown117 commented on tests/test_client.py
> +class TestClient:
Other than matching the original tests not really. It should work the same either way, with some minor refactoring.

2024-11-18 22:46 UTC, kyrofa commented on tests/test_client.py
> +class TestClient:
Scrap the format of the original tests. Focus on establishing a pattern to follow for the rest of the codebase.

2024-11-19 16:28 UTC, kyrofa commented on requirements.txt
> +packaging==24.2
Is this a runtime requirement?

2024-11-19 17:57 UTC, kyrofa approved these changes
This looks great, thank you!

2024-11-19 22:56 UTC, merged